variables:
  GIT_STRATEGY: recursive
  GIT_DEPTH: "3"

build:mac:
  tags:
    - osx
  stage: build
  script:
    - echo "QMAKE_LFLAGS += -mmacosx-version-min=10.10 -isysroot /Developer/SDKs/MacOSX10.10.sdk" >> beldex-wallet-gui.pro
    - export MACOSX_DEPLOYMENT_TARGET=10.10
    - rm -f beldex/lib/libwallet_merged.a
    - rm -rf build
    - ./build.sh release-static
    - cp beldex/bin/beldexd build/release/bin
  artifacts:
    paths:
      - "build/release/bin"
build:linux:
  image: registry.gitlab.com/beldexcoin/beldex-gui:latest
  tags:
    - ubuntu
  stage: build
  script:
    - export USE_SINGLE_BUILDDIR=1
    - export ZMQ_INCLUDE_PATH=/usr/local/include/
    - export ZMQ_LIBRARY=/usr/local/libzmq/src/.libs/libzmq.a
    - rm -f beldex/lib/libwallet_merged.a
    - rm -rf build
    - ./build.sh release-static
    - cd build && make deploy
  artifacts:
    paths:
      - "build/release/bin"
build:windows:
  tags:
    - windows
  stage: build
  script:
    - export USE_SINGLE_BUILDDIR=1
    - source ./build.sh release-static
    - mkdir deploy-artifacts
    - ./windeploy_helper.sh build/release/bin Release
  artifacts:
    paths:
      - "build/release/bin"
